# Generated by Django 4.1.10 on 2023-09-21 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='user',
        ),
        migrations.RemoveField(
            model_name='invoicedetail',
            name='user',
        ),
    ]
